version: '3.9'
services:
  op-geth:
    restart: unless-stopped
    stop_grace_period: 300s
    stop_signal: SIGINT
    container_name: cel2-op-geth
    image: us-west1-docker.pkg.dev/devopsre/celo-blockchain-public/op-geth:celo-v2.0.0-rc4
    entrypoint: /scripts/start-op-geth.sh
    env_file: ./alfajores/alfajores.env
    volumes:
      - ./alfajores/config:/chainconfig
      - ./geth-data:/geth
      - ./scripts/:/scripts
      - shared:/shared
    ports:
      - '127.0.0.1:8545:8545'
      - '127.0.0.1:8546:8546'
      - '127.0.0.1:8551:8551'
      - '30303:30303'
      - '30303:30303/udp'
    networks:
    - cel2
  op-node:
    restart: unless-stopped
    stop_grace_period: 300s
    stop_signal: SIGINT
    container_name: cel2-op-node
    image: us-west1-docker.pkg.dev/devopsre/celo-blockchain-public/op-node:celo-v2.0.0-rc4
    env_file: ./alfajores/alfajores.env
    entrypoint: /scripts/start-op-node.sh
    volumes:
      - ./alfajores/config:/chainconfig
      - ./scripts/:/scripts
      - shared:/shared
    ports:
      - '127.0.0.1:9545:9545'
      - '9003:9003'
      - '9003:9003/udp'
    depends_on:
      op-geth:
        condition: service_started      
    networks:
    - cel2

networks:
  cel2:
    external: true
