version: '3.9'
services:
  watchtower:
    image: containrrr/watchtower:latest
    command: --cleanup --label-enable -i 21600
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  cel2-op-geth:
    init: true
    user: root
    restart: unless-stopped
    container_name: cel2-op-geth
    image: us-west1-docker.pkg.dev/devopsre/celo-blockchain-public/op-geth:celo8
    command:
      --rollup.sequencerhttp https://sequencer.alfajores.celo-testnet.org
      --rollup.disabletxpoolgossip
      --gcmode full
      --networkid 44787
      --snapshot
      --verbosity 3
      --syncmode snap
      --cache.preimages
      --authrpc.addr 0.0.0.0
      --authrpc.port 8551
      --authrpc.jwtsecret /datadir/jwt.hex
      --http
      --http.addr 0.0.0.0
      --http.api eth,net,web3,txpool,debug
      --ws
      --ws.addr 0.0.0.0
      --ws.api eth,net,web3,txpool
      --datadir /datadir
      --authrpc.vhosts '*'
      --http.corsdomain '*'
      --http.vhosts '*'
      --ws.origins '*'
      --bootnodes enode://ac0f42fa46f8cc10bd02a103894d71d495537465133e7c442bc02dc76721a5f41761cc2d8c69e7ba1b33e14e28f516436864d3e0836e2dcdaf032387f72447dd@34.83.164.192:30303,enode://596002969b8b269a4fa34b4709b9600b64201e7d02e2f5f1350affd021b0cbda6ce2b913ebe24f0fb1edcf66b6c730a8a3b02cd940f4de995f73d3b290a0fc92@34.82.177.77:30303,enode://3619455064ef1ce667171bba1df80cfd4c097f018cf0205aaad496f0d509611b7c40396893d9e490ee390cd098888279e177a4d9bb09c58387bb0a6031d237f1@34.19.90.27:30303,enode://e3c54db6004a92d4ee87504f073f3234a25759b485274cc224037e3e5ee792f3b482c3f4fffcb764af6e1859a1aea9710b71e1991e32c1dee7f40352124bb182@35.233.249.87:30303,enode://674410b34fd54c8406a4f945292b96111688d4bab49aecdc34b4f1b346891f4673dcb03ed44c38ab467ef7bec0b20f6031ad88aa1d35ce1333b343d00fa19fb1@34.168.43.76:30303
    volumes:
      - ./cel2-chaindata:/datadir
    labels:
      - com.centurylinklabs.watchtower.enable=true      
    ports:
      - '127.0.0.1:8545:8545'
      - '127.0.0.1:8546:8546'
      - '127.0.0.1:8551:8551'
      - '30303:30303'
      - '30303:30303/udp'
    networks:
    - cel2
    stop_grace_period: 300s
    stop_signal: SIGINT
  cel2-op-node:
    init: true
    user: root
    restart: unless-stopped
    container_name: cel2-op-node
    image: us-west1-docker.pkg.dev/devopsre/celo-blockchain-public/op-node:celo9
    command:
      op-node
      --l1.trustrpc
      --l1 https://ethereum-holesky-rpc.publicnode.com
      --l1.beacon https://ethereum-holesky-beacon-api.publicnode.com 
      --l2 http://cel2-op-geth:8551
      --l2.jwt-secret /data/jwt.hex
      --rollup.load-protocol-versions
      --rollup.config /data/rollup.json
      --verifier.l1-confs 4
      --rpc.addr 0.0.0.0
      --rpc.port 9545
      --p2p.listen.tcp 9222
      --p2p.listen.udp 9222
      --p2p.priv.path /data/op-node_p2p_priv.txt
      --p2p.static /ip4/35.197.25.52/tcp/9222/p2p/16Uiu2HAmQEdyLRSAVZDr5SqbJ1RnKmNDhtQJcEKmemrVxe4FxKwR,/ip4/34.105.22.4/tcp/9222/p2p/16Uiu2HAm1SZBDSugT5MMu7vBY8auDgfZFNhoDeXPLc9Me5FsAxwT,/ip4/34.83.209.168/tcp/9222/p2p/16Uiu2HAmGJAiUX6HLSo4nLh8T984qxzokwL23cVsYuNZy2SrK7C6,/ip4/34.83.214.149/tcp/9222/p2p/16Uiu2HAmAko2Kr3eAjM7tnshtEhYrxQYfKUvN2kwiygeFoBAoi8S,/ip4/34.169.5.52/tcp/9222/p2p/16Uiu2HAmKc6YKHzYgsjBDaj36uAufxpgZFgrzDqVBt6zTPwdhhJD
      --altda.enabled
      --altda.da-server https://eigenda-proxy.alfajores.celo-testnet.org
      --altda.da-service
      --altda.verify-on-read false
    volumes:
      - ./cel2-rollupdata:/data
    labels:
      - com.centurylinklabs.watchtower.enable=true      
    ports:
      - '127.0.0.1:9545:9545'
      - '9222:9222'
      - '9222:9222/udp'
    networks:
    - cel2
    stop_grace_period: 300s
    stop_signal: SIGINT    

networks:
  cel2:
    external: true
