services:
  otel-collector:
    image: victoriametrics/vmagent:v1.118.0
    restart: unless-stopped
    volumes:
      - vmagentdata:/vmagentdata
      - ./vmagent.yaml:/etc/vmagent.yaml
    command:
      - --promscrape.config=/etc/vmagent.yaml
      - --remoteWrite.url=http://victoriametrics:8428/api/v1/write
    networks:
      - cel2

volumes:
  vmagent:
    driver: local

networks:
  cel2:
    external: true
