version: '3.9'
services:
  celochain:
    init: true
    user: root  
    restart: unless-stopped
    container_name: celochain
    image: us.gcr.io/celo-org/geth:alfajores
    command:
      --alfajores
      --verbosity 3
      --syncmode full
      --gcmode archive
      --maxpeers 75
      --txlookuplimit=0
      --cache.preimages
      --http
      --http.addr 0.0.0.0
      --http.api eth,net,web3,txpool
      --ws
      --ws.addr 0.0.0.0
      --ws.api eth,net,web3,txpool
      --graphql
      --datadir /root/.celo
      --http.corsdomain '*'
      --http.vhosts '*'
      --ws.origins '*'
      --graphql.corsdomain '*'
      --graphql.vhosts '*'
    volumes:
      - ./data:/root/.celo
    ports:
      - '8545:8545'
      - '8546:8546'
      - '30303:30303'
      - '30303:30303/udp'
    networks:
      - celo
networks:
  celo:
    driver: bridge